["target.x86_64-unknown-linux-gnu"]
linker = '/usr/bin/clang'
rustflags = [
    '-C',
    'link-arg=--lld-path=/usr/bin/mold',
]

["target.x86_64-unknown-linux-musl"]
linker = '/usr/bin/clang'
rustflags = [
    '-C',
    'link-arg=--lld-path=/usr/bin/mold',
]

["target.x86_64-apple-darwin"]
linker = '/usr/bin/clang'
rustflags = [
    '-C',
    'link-arg=--lld-path=/usr/bin/zld',
]

["target.aarch64-apple-darwin"]
linker = '/usr/bin/clang'
rustflags = [
    '-C',
    'link-arg=--lld-path=/usr/bin/zld',
]

[build]
rustc-wrapper = ''
rustflags = []
